<?php $catalogSearchHelper = $this->helper('catalogsearch'); ?>
<form id="search_mini_form" role="search"
      action="<?php echo $catalogSearchHelper->getResultUrl() ?>" method="get">

    <div class="searchbar text-center">

        <input id="search" type="text" name="<?php echo $catalogSearchHelper->getQueryParamName() ?>"
               value="<?php echo $catalogSearchHelper->getEscapedQueryText() ?>"
               maxlength="<?php echo $catalogSearchHelper->getMaxQueryLength(); ?>"
               placeholder="<?php echo $this->__('Pretraga...') ?>"/>

        <button type="submit" class="btn"><i class="fas fa-search"></i></button>

    </div>

    <div id="search_autocomplete" class="search-autocomplete"></div>
</form>
<script type="text/javascript">
    //<![CDATA[
    var searchForm = new Varien.searchForm('search_mini_form', 'search',
        '<?php echo $this->__('Pretraga...') ?>');
    searchForm.initAutocomplete('<?php echo $catalogSearchHelper->getSuggestUrl() ?>', 'search_autocomplete');
    //]]>
</script>