<div class="container header-container">
    <div class="row">
        <div class="col-md-3">
            <a href="<?php echo $this->getUrl('') ?>" title="<?php echo $this->getLogoAlt() ?>" class="logo">
                <img src="<?php echo $this->getLogoSrc() ?>" alt="<?php echo $this->getLogoAlt() ?>"/>
            </a>
        </div>
        <div class="col-md-6">
            <?php echo $this->getChildHtml('quick_links') ?>
            <?php echo $this->getChildHtml('topSearch') ?>
        </div>
    </div>
    <nav>
        <div class="row">
        <div class="col-md-9">
            <?php echo $this->getChildHtml('topMenu') ?>
        </div>
        <div class="col-md-3">

        </div>
    </div>
    </nav>
</div>


